/**
 * Audio Effects — video effect definitions.
 *
 * Pure data consumed by the effects panel (renderer) and the FFmpeg export
 * pipeline (Electron main). Add a new effect by appending an entry here;
 * give transitions an `xfade` name so the export pipeline can render them.
 * Optional per-effect icons go in components/effectIcons.ts.
 */

import type { VideoEffectCategory } from '../types';

export const audioCategory: VideoEffectCategory = {
  key: 'audio',
  name: 'Audio Effects',
  effects: [
    {
      id: 'gain',
      name: 'Gain',
      type: 'audio-effect',
      description: 'Adjust volume',
      defaultParams: { gain: 0 },
    },
    {
      id: 'equalizer',
      name: 'Equalizer',
      type: 'audio-effect',
      description: 'Frequency equalizer',
      defaultParams: { low: 0, mid: 0, high: 0 },
    },
    {
      id: 'compressor',
      name: 'Compressor',
      type: 'audio-effect',
      description: 'Dynamic range compression',
      defaultParams: { threshold: -20, ratio: 4 },
    },
    {
      id: 'reverb',
      name: 'Reverb',
      type: 'audio-effect',
      description: 'Add reverb effect',
      defaultParams: { decay: 2, wet: 30 },
    },
    {
      id: 'noise-reduction',
      name: 'Noise Reduction',
      type: 'audio-effect',
      description: 'Reduce background noise',
      defaultParams: { reduction: 50 },
    },
    {
      id: 'de-esser',
      name: 'DeEsser',
      type: 'audio-effect',
      description: 'Remove harsh sibilance (s/sh sounds)',
      defaultParams: { frequency: 6000, threshold: -20, reduction: 10 },
    },
    {
      id: 'parametric-eq',
      name: 'Parametric EQ',
      type: 'audio-effect',
      description: 'Professional 5-band parametric equalizer',
      defaultParams: { band1Frequency: 80, band1Gain: 0, band1Q: 0.7, band2Frequency: 250, band2Gain: 0, band2Q: 1.0, band3Frequency: 1000, band3Gain: 0, band3Q: 1.0, band4Frequency: 4000, band4Gain: 0, band4Q: 1.0, band5Frequency: 12000, band5Gain: 0, band5Q: 0.7, },
    },
    {
      id: 'multiband-compressor',
      name: 'Multiband Compressor',
      type: 'audio-effect',
      description: 'Multi-band dynamic range compression',
      defaultParams: { bands: 3, lowFreq: 200, highFreq: 2000 },
    },
    {
      id: 'convolution-reverb',
      name: 'Convolution Reverb',
      type: 'audio-effect',
      description: 'Impulse-response based reverb',
      defaultParams: { impulse: 'hall', wet: 30, dry: 100 },
    },
    {
      id: 'chorus',
      name: 'Chorus',
      type: 'audio-effect',
      description: 'Chorus modulation effect',
      defaultParams: { rate: 1.5, depth: 50, mix: 50 },
    },
    {
      id: 'flanger',
      name: 'Flanger',
      type: 'audio-effect',
      description: 'Flanger modulation effect',
      defaultParams: { rate: 0.5, depth: 80, feedback: 50, mix: 50 },
    },
    {
      id: 'phaser',
      name: 'Phaser',
      type: 'audio-effect',
      description: 'Phaser modulation effect',
      defaultParams: { rate: 0.3, depth: 60, stages: 4, mix: 50 },
    },
    {
      id: 'amplify',
      name: 'Amplify',
      type: 'audio-effect',
      description: 'Volume amplification',
      defaultParams: { gain: 0 },
    },
    {
      id: 'hard-limiter',
      name: 'Hard Limiter',
      type: 'audio-effect',
      description: 'Hard limiter to prevent clipping',
      defaultParams: { ceiling: -0.1, release: 10 },
    },
    {
      id: 'tube-compressor',
      name: 'Tube-modeled Compressor',
      type: 'audio-effect',
      description: 'Warm tube-style compression',
      defaultParams: { threshold: -20, ratio: 4, drive: 3 },
    },
    {
      id: 'dynamics',
      name: 'Dynamics',
      type: 'audio-effect',
      description: 'Dynamics processing (gate/expander/compressor)',
      defaultParams: { gate: -60, attack: 5, release: 50 },
    },
    {
      id: 'analog-delay',
      name: 'Analog Delay',
      type: 'audio-effect',
      description: 'Warm analog-style delay',
      defaultParams: { delayTime: 250, feedback: 30, mix: 40 },
    },
    {
      id: 'bass',
      name: 'Bass',
      type: 'audio-effect',
      description: 'Low frequency boost/cut',
      defaultParams: { gain: 0, frequency: 200 },
    },
    {
      id: 'treble',
      name: 'Treble',
      type: 'audio-effect',
      description: 'High frequency boost/cut',
      defaultParams: { gain: 0, frequency: 4000 },
    },
    {
      id: 'graphic-eq',
      name: 'Graphic Equalizer',
      type: 'audio-effect',
      description: '10/20/30 band graphic equalizer',
      defaultParams: { bands: 10 },
    },
    {
      id: 'notch-filter',
      name: 'Notch Filter',
      type: 'audio-effect',
      description: 'Remove specific frequency (hum/buzz)',
      defaultParams: { frequency: 60, q: 10, gain: -60 },
    },
    {
      id: 'adaptive-noise-reduction',
      name: 'Adaptive Noise Reduction',
      type: 'audio-effect',
      description: 'Adaptive noise floor detection and reduction',
      defaultParams: { reduction: 50, sensitivity: 50 },
    },
    {
      id: 'dehummer',
      name: 'DeHummer',
      type: 'audio-effect',
      description: 'Remove 50/60Hz hum noise',
      defaultParams: { frequency: 60, harmonics: 5, reduction: 40 },
    },
    {
      id: 'denoise',
      name: 'DeNoise',
      type: 'audio-effect',
      description: 'Noise removal',
      defaultParams: { reduction: 50 },
    },
    {
      id: 'studio-reverb',
      name: 'Studio Reverb',
      type: 'audio-effect',
      description: 'Studio reverb simulation',
      defaultParams: { roomSize: 50, decay: 2, wet: 30, predelay: 20 },
    },
    {
      id: 'vocal-enhancer',
      name: 'Vocal Enhancer',
      type: 'audio-effect',
      description: 'Vocal clarity and presence enhancement',
      defaultParams: { presence: 50, clarity: 50, warmth: 30 },
    },
    {
      id: 'stereo-expander',
      name: 'Stereo Expander',
      type: 'audio-effect',
      description: 'Widen stereo image',
      defaultParams: { width: 50 },
    },
    {
      id: 'fft-filter',
      name: 'FFT Filter',
      type: 'audio-effect',
      description: 'FFT-based frequency filter',
      defaultParams: { type: 'lowpass', frequency: 1000, q: 1 },
    },
    {
      id: 'scientific-filter',
      name: 'Scientific Filter',
      type: 'audio-effect',
      description: 'Scientific audio filter (Butterworth/Bessel/Chebyshev)',
      defaultParams: { filterType: 'butterworth', order: 2, frequency: 1000 },
    },
    {
      id: 'swap-channels',
      name: 'Swap Channels',
      type: 'audio-effect',
      description: 'Swap left/right audio channels',
      defaultParams: {},
    },
    {
      id: 'fill-left-right',
      name: 'Fill Left/Right',
      type: 'audio-effect',
      description: 'Fill mono to both channels',
      defaultParams: { fillWith: 'left' },
    },
    {
      id: 'invert-audio',
      name: 'Invert',
      type: 'audio-effect',
      description: 'Invert audio phase',
      defaultParams: { invertLeft: true, invertRight: true },
    },
    {
      id: 'downmixer',
      name: 'Downmixer',
      type: 'audio-effect',
      description: 'Downmix surround to stereo/mono',
      defaultParams: { output: 'stereo' },
    },
    {
      id: 'balance',
      name: 'Balance',
      type: 'audio-effect',
      description: 'Left/right balance control',
      defaultParams: { balance: 0 },
    },
  ],
};
