/**
 * Transitions — video effect definitions.
 *
 * Pure data consumed by the effects panel (renderer) and the FFmpeg export
 * pipeline (Electron main). Add a new effect by appending an entry here;
 * give transitions an `xfade` name so the export pipeline can render them.
 * Optional per-effect icons go in components/effectIcons.ts.
 */

import type { VideoEffectCategory } from '../types';

export const transitionsCategory: VideoEffectCategory = {
  key: 'transitions',
  name: 'Transitions',
  effects: [
    {
      id: 'fade',
      name: 'Fade',
      type: 'transition',
      description: 'Smooth fade in/out',
      defaultParams: { duration: 0.5 },
      xfade: 'fade',
    },
    {
      id: 'dissolve',
      name: 'Dissolve',
      type: 'transition',
      description: 'Cross dissolve between clips',
      defaultParams: { duration: 0.5 },
      xfade: 'dissolve',
    },
    {
      id: 'wipe',
      name: 'Wipe',
      type: 'transition',
      description: 'Wipe transition',
      defaultParams: { duration: 0.5, direction: 0 },
      xfade: 'wipeleft',
    },
    {
      id: 'slide',
      name: 'Slide',
      type: 'transition',
      description: 'Slide in/out',
      defaultParams: { duration: 0.5, direction: 0 },
      xfade: 'slideleft',
    },
    {
      id: 'zoom',
      name: 'Zoom',
      type: 'transition',
      description: 'Zoom transition',
      defaultParams: { duration: 0.5, scale: 1.2 },
      xfade: 'zoomin',
    },
    {
      id: 'blur-transition',
      name: 'Blur',
      type: 'transition',
      description: 'Blur transition',
      defaultParams: { duration: 0.5, intensity: 20 },
      xfade: 'hblur',
    },
    {
      id: 'dip-to-black',
      name: 'Dip to Black',
      type: 'transition',
      description: 'Dip through black',
      defaultParams: { duration: 0.5 },
      xfade: 'fadeblack',
    },
    {
      id: 'dip-to-white',
      name: 'Dip to White',
      type: 'transition',
      description: 'Dip through white',
      defaultParams: { duration: 0.5 },
      xfade: 'fadewhite',
    },
    {
      id: 'push',
      name: 'Push',
      type: 'transition',
      description: 'Push clip in a direction',
      defaultParams: { duration: 0.5, direction: 'left' },
      xfade: 'coverleft',
    },
    {
      id: 'film-dissolve',
      name: 'Film Dissolve',
      type: 'transition',
      description: 'Film gamma cross dissolve',
      defaultParams: { duration: 0.5 },
      xfade: 'fadegrays',
    },
    {
      id: 'tr-iris',
      name: 'Iris',
      type: 'transition',
      description: 'Circular iris wipe transition',
      defaultParams: { duration: 0.5, transitionType: 'iris' },
      xfade: 'circlecrop',
    },
    {
      id: 'tr-clock-wipe',
      name: 'Clock Wipe',
      type: 'transition',
      description: 'Radial clock wipe transition',
      defaultParams: { duration: 0.5, transitionType: 'clock-wipe' },
      xfade: 'radial',
    },
    {
      id: 'tr-gradient-wipe',
      name: 'Gradient Wipe',
      type: 'transition',
      description: 'Soft edge gradient wipe transition',
      defaultParams: { duration: 0.5, transitionType: 'gradient-wipe' },
      xfade: 'hblur',
    },
    {
      id: 'additive-dissolve',
      name: 'Additive Dissolve',
      type: 'transition',
      description: 'Brightness-additive dissolve',
      defaultParams: { duration: 0.5 },
      xfade: 'distance',
    },
    {
      id: 'non-additive-dissolve',
      name: 'Non-Additive Dissolve',
      type: 'transition',
      description: 'Non-additive dissolve',
      defaultParams: { duration: 0.5 },
      xfade: 'pixelize',
    },
    {
      id: 'iris-box',
      name: 'Iris Box',
      type: 'transition',
      description: 'Box iris wipe',
      defaultParams: { duration: 0.5 },
      xfade: 'rectcrop',
    },
    {
      id: 'iris-cross',
      name: 'Iris Cross',
      type: 'transition',
      description: 'Cross iris wipe',
      defaultParams: { duration: 0.5 },
      xfade: 'circlecrop',
    },
    {
      id: 'iris-diamond',
      name: 'Iris Diamond',
      type: 'transition',
      description: 'Diamond iris wipe',
      defaultParams: { duration: 0.5 },
      xfade: 'circlecrop',
    },
    {
      id: 'iris-star',
      name: 'Iris Star',
      type: 'transition',
      description: 'Star iris wipe',
      defaultParams: { duration: 0.5 },
      xfade: 'circlecrop',
    },
    {
      id: 'iris-points',
      name: 'Iris Points',
      type: 'transition',
      description: 'Polygon iris wipe',
      defaultParams: { duration: 0.5 },
      xfade: 'circlecrop',
    },
    {
      id: 'band-slide',
      name: 'Band Slide',
      type: 'transition',
      description: 'Band slide transition',
      defaultParams: { duration: 0.5 },
      xfade: 'squeezeh',
    },
    {
      id: 'center-merge',
      name: 'Center Merge',
      type: 'transition',
      description: 'Center merge transition',
      defaultParams: { duration: 0.5 },
      xfade: 'horzclose',
    },
    {
      id: 'center-split',
      name: 'Center Split',
      type: 'transition',
      description: 'Center split transition',
      defaultParams: { duration: 0.5 },
      xfade: 'horzopen',
    },
    {
      id: 'slash-slide',
      name: 'Slash Slide',
      type: 'transition',
      description: 'Diagonal slash slide',
      defaultParams: { duration: 0.5 },
      xfade: 'diagtl',
    },
    {
      id: 'split',
      name: 'Split',
      type: 'transition',
      description: 'Split transition',
      defaultParams: { duration: 0.5 },
      xfade: 'vertopen',
    },
    {
      id: 'swap',
      name: 'Swap',
      type: 'transition',
      description: 'Swap transition',
      defaultParams: { duration: 0.5 },
      xfade: 'hlslice',
    },
    {
      id: 'swirl',
      name: 'Swirl',
      type: 'transition',
      description: 'Swirl slide transition',
      defaultParams: { duration: 0.5 },
      // FFmpeg has no swirl xfade; radial is the closest rotational sweep.
      // Without an xfade the export pipeline silently hard-cuts.
      xfade: 'radial',
    },
    {
      id: 'whip-turn',
      name: 'Whip Turn',
      type: 'transition',
      description: 'Fast whip turn',
      defaultParams: { duration: 0.5 },
      xfade: 'smoothright',
    },
    {
      id: 'sliding-bands',
      name: 'Sliding Bands',
      type: 'transition',
      description: 'Sliding bands transition',
      defaultParams: { duration: 0.5 },
      xfade: 'squeezev',
    },
    {
      id: 'barn-doors',
      name: 'Barn Doors',
      type: 'transition',
      description: 'Barn doors opening wipe',
      defaultParams: { duration: 0.5 },
      xfade: 'horzopen',
    },
    {
      id: 'pinwheel',
      name: 'Pinwheel',
      type: 'transition',
      description: 'Pinwheel wipe',
      defaultParams: { duration: 0.5 },
      xfade: 'radial',
    },
    {
      id: 'radial-wipe',
      name: 'Radial Wipe',
      type: 'transition',
      description: 'Radial wipe transition',
      defaultParams: { duration: 0.5 },
      xfade: 'radial',
    },
    {
      id: 'venetian-blinds',
      name: 'Venetian Blinds',
      type: 'transition',
      description: 'Venetian blinds wipe',
      defaultParams: { duration: 0.5 },
      xfade: 'vdslice',
    },
    {
      id: 'band-wipe',
      name: 'Band Wipe',
      type: 'transition',
      description: 'Band wipe transition',
      defaultParams: { duration: 0.5 },
      xfade: 'wipetl',
    },
    {
      id: 'checker-wipe',
      name: 'Checker Wipe',
      type: 'transition',
      description: 'Checker pattern wipe',
      defaultParams: { duration: 0.5 },
      xfade: 'pixelize',
    },
    {
      id: 'checkerboard-wipe',
      name: 'Checkerboard Wipe',
      type: 'transition',
      description: 'Checkerboard wipe transition',
      defaultParams: { duration: 0.5 },
      xfade: 'pixelize',
    },
    {
      id: 'inset',
      name: 'Inset',
      type: 'transition',
      description: 'Inset transition',
      defaultParams: { duration: 0.5 },
      xfade: 'rectcrop',
    },
    {
      id: 'random-blocks',
      name: 'Random Blocks',
      type: 'transition',
      description: 'Random blocks dissolve',
      defaultParams: { duration: 0.5 },
      xfade: 'pixelize',
    },
    {
      id: 'random-wipe',
      name: 'Random Wipe',
      type: 'transition',
      description: 'Random pattern wipe',
      defaultParams: { duration: 0.5 },
      xfade: 'wipetl',
    },
    {
      id: 'wedge-wipe',
      name: 'Wedge Wipe',
      type: 'transition',
      description: 'Wedge-shaped wipe',
      defaultParams: { duration: 0.5 },
      xfade: 'wipetl',
    },
    {
      id: 'wipe-basic',
      name: 'Wipe',
      type: 'transition',
      description: 'Basic wipe transition',
      defaultParams: { duration: 0.5 },
      xfade: 'wipeleft',
    },
    {
      id: 'linear-wipe-transition',
      name: 'Linear Wipe',
      type: 'transition',
      description: 'Linear wipe transition',
      defaultParams: { duration: 0.5, angle: 0 },
      xfade: 'wipeleft',
    },
    {
      id: 'multi-spin',
      name: 'Multi-Spin',
      type: 'transition',
      description: 'Multi-spin rotation transition',
      defaultParams: { duration: 0.5 },
      xfade: 'zoomin',
    },
    {
      id: 'slide-basic',
      name: 'Slide',
      type: 'transition',
      description: 'Basic slide transition',
      defaultParams: { duration: 0.5 },
      xfade: 'slideleft',
    },
    {
      id: 'cross-zoom',
      name: 'Cross Zoom',
      type: 'transition',
      description: 'Cross zoom transition',
      defaultParams: { duration: 0.5 },
      xfade: 'zoomin',
    },
    {
      id: 'zoom-basic',
      name: 'Zoom',
      type: 'transition',
      description: 'Basic zoom transition',
      defaultParams: { duration: 0.5 },
      xfade: 'zoomin',
    },
  ],
};
