/**
 * Icon adornments for video effect definitions (renderer-only).
 *
 * Effect/category definitions are pure data in ../effects/definitions; icons
 * stay here so the definitions can also run in the Electron main process.
 * A new effect without an entry falls back to its category icon.
 */

import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  ArrowDownCircle,
  ArrowRightLeft,
  ArrowUpCircle,
  BarChart2,
  BarChart3,
  Blend,
  Box,
  Building2,
  ChartScatter,
  Circle,
  CircleDashed,
  CircleDot,
  Clapperboard,
  Clock,
  CloudFog,
  Contrast,
  Crosshair,
  Cylinder,
  Droplets,
  Eraser,
  Eye,
  Film,
  Filter,
  FilterX,
  Gauge,
  Globe,
  Grid3x3,
  Hash,
  Layers,
  Maximize2,
  Mic,
  Monitor,
  Mountain,
  Move,
  MoveRight,
  Paintbrush,
  Palette,
  Pipette,
  Radio,
  RotateCcw,
  ScanLine,
  ShieldAlert,
  ShieldCheck,
  Shuffle,
  Sliders,
  SlidersHorizontal,
  Sparkles,
  Square,
  Sun,
  SunDim,
  SunMedium,
  SwatchBook,
  Triangle,
  Volume2,
  VolumeX,
  Wand2,
  Waves,
  Zap,
} from 'lucide-react';

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  transitions: ArrowRightLeft,
  colorCorrection: Palette,
  stylize: Wand2,
  sharpenBlur: Droplets,
  generate: Sparkles,
  distort: Circle,
  perspective: Box,
  keying: Layers,
  time: Clock,
  utility: Wand2,
  transitionStyle: ArrowRightLeft,
  transformEffects: Move,
  audio: Volume2,
  adjust: Sliders,
  colorCorrectionAdvanced: Palette,
  channel: Layers,
  noiseGrain: Sparkles,
  stylizeAdvanced: Wand2,
  utilityAdvanced: Wand2,
  vrImmersive: Globe,
};

export const EFFECT_ICONS: Record<string, LucideIcon> = {
  'fade': Eye,
  'dissolve': Blend,
  'wipe': ArrowRightLeft,
  'slide': Move,
  'zoom': Maximize2,
  'blur-transition': Droplets,
  'dip-to-black': CircleDot,
  'dip-to-white': Sun,
  'push': MoveRight,
  'film-dissolve': Film,
  'tr-iris': CircleDashed,
  'tr-clock-wipe': Clock,
  'tr-gradient-wipe': SlidersHorizontal,
  'additive-dissolve': Blend,
  'non-additive-dissolve': Blend,
  'iris-box': CircleDashed,
  'iris-cross': CircleDashed,
  'iris-diamond': CircleDashed,
  'iris-star': CircleDashed,
  'iris-points': CircleDashed,
  'band-slide': ArrowRightLeft,
  'center-merge': ArrowRightLeft,
  'center-split': ArrowRightLeft,
  'slash-slide': ArrowRightLeft,
  'split': ArrowRightLeft,
  'swap': ArrowRightLeft,
  'swirl': RotateCcw,
  'whip-turn': RotateCcw,
  'sliding-bands': ArrowRightLeft,
  'barn-doors': ArrowRightLeft,
  'pinwheel': RotateCcw,
  'radial-wipe': Clock,
  'venetian-blinds': ArrowRightLeft,
  'band-wipe': ArrowRightLeft,
  'checker-wipe': Grid3x3,
  'checkerboard-wipe': Grid3x3,
  'inset': Square,
  'random-blocks': Grid3x3,
  'random-wipe': Shuffle,
  'wedge-wipe': Triangle,
  'wipe-basic': ArrowRightLeft,
  'linear-wipe-transition': ArrowRightLeft,
  'multi-spin': RotateCcw,
  'slide-basic': ArrowRightLeft,
  'cross-zoom': Maximize2,
  'zoom-basic': Maximize2,
  'brightness': Sun,
  'contrast': Contrast,
  'saturation': Droplets,
  'hue': Palette,
  'color-pass': Pipette,
  'color-replace': SwatchBook,
  'leave-color': Pipette,
  'tint': Paintbrush,
  'channel-mixer': Blend,
  'blur': Droplets,
  'sepia': Palette,
  'grayscale': CircleDot,
  'invert': RotateCcw,
  'vignette': CircleDot,
  'mosaic': Grid3x3,
  'posterize': Layers,
  'find-edges': ScanLine,
  'noise': ChartScatter,
  'alpha-glow': Sun,
  'emboss': Mountain,
  'solarize': SunMedium,
  'strobe-effect': Zap,
  'glow': Sun,
  'directional-blur': MoveRight,
  'unsharp-mask': SlidersHorizontal,
  'camera-blur': CircleDot,
  'channel-blur': Layers,
  'compound-blur': Blend,
  'sharpen': Contrast,
  'gaussian-blur': Droplets,
  'zoom-blur': Maximize2,
  'anti-alias-blur': Droplets,
  'grid-generate': Grid3x3,
  'lens-distortion': Circle,
  'corner-pin': Maximize2,
  'mirror': ArrowRightLeft,
  'offset': Move,
  'wave-warp': Waves,
  'transform-effect': Move,
  'motion-tile': Grid3x3,
  'ripple-distort': Waves,
  'basic-3d': Box,
  'drop-shadow': CloudFog,
  'luma-key': Sun,
  'color-key': Palette,
  'non-red-key': Eye,
  'ultra-key': Eye,
  'posterize-time': Clock,
  'crop-effect': Maximize2,
  'edge-feather': Droplets,
  'block-dissolve': Grid3x3,
  'linear-wipe': ArrowRightLeft,
  'venetian-blinds-effect': ArrowRightLeft,
  'strobe-light': Zap,
  'threshold': Contrast,
  'gradient-wipe-effect': SlidersHorizontal,
  'horizontal-flip': ArrowRightLeft,
  'vertical-flip': ArrowRightLeft,
  'flicker-removal': Wand2,
  'replicate': Grid3x3,
  'gain': Volume2,
  'equalizer': Waves,
  'compressor': Zap,
  'reverb': Waves,
  'noise-reduction': Wand2,
  'de-esser': FilterX,
  'parametric-eq': BarChart2,
  'multiband-compressor': BarChart2,
  'convolution-reverb': Waves,
  'chorus': Waves,
  'flanger': Waves,
  'phaser': Waves,
  'amplify': Volume2,
  'hard-limiter': ShieldAlert,
  'tube-compressor': Cylinder,
  'dynamics': Activity,
  'analog-delay': Clock,
  'bass': ArrowDownCircle,
  'treble': ArrowUpCircle,
  'graphic-eq': BarChart3,
  'notch-filter': Filter,
  'adaptive-noise-reduction': ShieldCheck,
  'dehummer': Zap,
  'denoise': VolumeX,
  'studio-reverb': Building2,
  'vocal-enhancer': Mic,
  'stereo-expander': Maximize2,
  'fft-filter': BarChart2,
  'scientific-filter': Gauge,
  'swap-channels': Shuffle,
  'fill-left-right': Radio,
  'invert-audio': Shuffle,
  'downmixer': ArrowDownCircle,
  'balance': SlidersHorizontal,
  'auto-color': Wand2,
  'auto-contrast': Contrast,
  'auto-levels': BarChart3,
  'levels': BarChart3,
  'shadow-highlight': Sun,
  'proc-amp': Monitor,
  'gamma-correction': SunDim,
  'convolution-kernel': Grid3x3,
  'extract-effect': Eraser,
  'asc-cdl': Clapperboard,
  'brightness-contrast': Sun,
  'change-color': Pipette,
  'change-to-color': Pipette,
  'color-balance-hls': Palette,
  'equalize': BarChart3,
  'fast-color-corrector': Gauge,
  'luma-corrector': Contrast,
  'luma-curve': ChartScatter,
  'rgb-color-corrector': Palette,
  'rgb-curves': ChartScatter,
  'three-way-color-corrector': Palette,
  'video-limiter': ShieldAlert,
  'arithmetic': Hash,
  'calculations': Hash,
  'solid-composite': Square,
  'black-and-white': Contrast,
  'color-balance-rgb': Palette,
  'dust-and-scratches': Eraser,
  'median': Sparkles,
  'noise-hls': Sparkles,
  'noise-alpha': Sparkles,
  'reduce-interlace-flicker': ScanLine,
  'color-emboss': Mountain,
  'cineon-converter': Film,
  'sdr-conform': Monitor,
  'vr-projection': Globe,
  'vr-rotate-sphere': RotateCcw,
  'vr-de-noise': Eraser,
  'vr-color-gradients': Palette,
  'vr-glow': SunMedium,
  'vr-sharpen': Crosshair,
  'vr-blur': Droplets,
};
